services:
  postgres:
    image: postgres:17.5-alpine
    container_name: pg-sidetool
    env_file:
      - .env.development.local
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
